package io.github.guillermodubon.coachgym.notification;

/** Bounded, provider-neutral failure taxonomy for transactional delivery. */
public enum EmailDeliveryFailureCode {
    DELIVERY_DISABLED,
    RECIPIENT_UNAVAILABLE,
    SOURCE_NOT_FOUND,
    ATTACHMENT_UNAVAILABLE,
    ATTACHMENT_INTEGRITY_FAILED,
    VALIDATION_FAILED,
    DUPLICATE_DELIVERY,
    DELIVERY_STATE_CONFLICT,
    DELIVERY_VERSION_CONFLICT,
    RETRY_LIMIT_REACHED,
    TRANSPORT_TIMEOUT,
    TRANSPORT_AUTHENTICATION_FAILED,
    TRANSPORT_CONFIGURATION_FAILED,
    TRANSPORT_REJECTED,
    AMBIGUOUS_TRANSPORT_OUTCOME,
    DATA_ACCESS_FAILED,
    COMPOSITION_FAILED,
    UNEXPECTED_FAILURE
}
