package io.github.guillermodubon.coachgym.equipment.web;

import io.github.guillermodubon.coachgym.auth.CoachGymUserPrincipal;
import io.github.guillermodubon.coachgym.equipment.EquipmentDetails;
import io.github.guillermodubon.coachgym.equipment.application.EquipmentApplicationService;
import io.github.guillermodubon.coachgym.equipment.application.EquipmentSearchQuery;
import io.github.guillermodubon.coachgym.equipment.application.exception.DuplicateSerialNumberException;
import io.github.guillermodubon.coachgym.equipment.application.exception.EquipmentCategoryInactiveException;
import io.github.guillermodubon.coachgym.equipment.application.exception.EquipmentCategoryNotFoundException;
import io.github.guillermodubon.coachgym.equipment.application.exception.EquipmentNotFoundException;
import io.github.guillermodubon.coachgym.equipment.application.exception.EquipmentStateConflictException;
import io.github.guillermodubon.coachgym.equipment.application.exception.EquipmentVersionConflictException;
import io.github.guillermodubon.coachgym.equipment.domain.EquipmentValidationException;
import io.github.guillermodubon.coachgym.shared.web.ApiProblemFactory;
import io.github.guillermodubon.coachgym.user.AuthenticatedActor;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.net.URI;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.util.UriComponentsBuilder;

@RestController
@RequestMapping("/api/v1/equipment")
@Tag(name = "Equipment", description = "Equipment catalog management.")
@SecurityRequirement(name = "sessionCookie")
class EquipmentController {

    private final EquipmentApplicationService equipmentService;

    EquipmentController(EquipmentApplicationService equipmentService) {
        this.equipmentService = equipmentService;
    }

    //POST /api/v1/equipment

    @PostMapping
    @Operation(summary = "Register new equipment",
            description = """
                Registers a new piece of equipment. ADMIN only.
                The equipment code (EQP-XXXXXX) is generated by the database
                and returned in the response; it cannot be supplied by the caller.
                Initial status is always AVAILABLE.
                """)
    @ApiResponse(responseCode = "201", description = "Equipment registered")
    @ApiResponse(responseCode = "400", description = "Validation failed")
    @ApiResponse(responseCode = "401", description = "Authentication required")
    @ApiResponse(responseCode = "403", description = "ADMIN role required or missing CSRF token")
    @ApiResponse(responseCode = "404", description = "Category not found")
    @ApiResponse(responseCode = "409", description = "Inactive category or duplicate serial number")
    ResponseEntity<EquipmentResponse> register(
            @Valid @RequestBody RegisterEquipmentRequest request,
            Authentication authentication,
            UriComponentsBuilder uriBuilder) {
        EquipmentDetails registered = equipmentService.register(
                request.toCommand(), actor(authentication));
        URI location = uriBuilder
                .path("/api/v1/equipment/{id}")
                .buildAndExpand(registered.id())
                .toUri();
        return ResponseEntity.created(location).body(EquipmentResponse.from(registered));
    }

    // PUT /api/v1/equipment/{id}

    @PutMapping("/{id}")
    @Operation(
            summary = "Update equipment",
            description = """
                Administratively updates the allowlisted fields of an existing
                equipment item.

                Required role: ADMIN.
                A valid CSRF token is required.
                Version is mandatory for optimistic locking.

                Immutable and server-managed fields such as id,
                equipmentNumber, equipmentCode, status, retirement fields,
                audit fields and timestamps are not part of the request
                contract and must not be supplied.

                Equipment is never physically deleted through this API.
        """)
    @ApiResponse(responseCode = "200", description = "Equipment updated")
    @ApiResponse(responseCode = "400", description = "Validation failed")
    @ApiResponse(responseCode = "401", description = "Authentication required")
    @ApiResponse(responseCode = "403", description = "ADMIN role required or missing CSRF token")
    @ApiResponse(responseCode = "404", description = "Equipment or category not found")
    @ApiResponse(responseCode = "409", description = "Version conflict, inactive category, or duplicate serial")
    EquipmentResponse update(
            @PathVariable UUID id,
            @Valid @RequestBody UpdateEquipmentRequest request,
            Authentication authentication) {
        return EquipmentResponse.from(
                equipmentService.update(request.toCommand(id), actor(authentication)));
    }

    //  GET /api/v1/equipment/{id}

    @GetMapping("/{id}")
    @Operation(summary = "Get equipment by ID")
    @ApiResponse(responseCode = "200", description = "Equipment returned")
    @ApiResponse(responseCode = "401", description = "Authentication required")
    @ApiResponse(responseCode = "403", description = "Insufficient permissions")
    @ApiResponse(responseCode = "404", description = "Equipment not found")
    EquipmentResponse findById(@PathVariable UUID id) {
        return EquipmentResponse.from(equipmentService.findById(id));
    }

    // GET /api/v1/equipment

    @GetMapping
    @Operation(summary = "List equipment",
            description = """
                Returns a paginated equipment catalog.
                Approved filters: categoryId, status (AVAILABLE|OUT_OF_SERVICE|RETIRED|MAINTENANCE),
                search (name ILIKE), location (location ILIKE).
                Approved sort fields: name (default), createdAt, status, id.
                Direction: asc (default), desc.
                Secondary sort is always id ASC for stable pagination.
                """)
    @ApiResponse(responseCode = "200", description = "Equipment list returned")
    @ApiResponse(responseCode = "400", description = "Invalid filter, sort, or pagination value")
    @ApiResponse(responseCode = "401", description = "Authentication required")
    @ApiResponse(responseCode = "403", description = "Insufficient permissions")
    EquipmentPageResponse findAll(
            @Parameter(description = "Filter by category UUID")
            @RequestParam(required = false) UUID categoryId,

            @Parameter(description = "Filter by status: AVAILABLE, OUT_OF_SERVICE, RETIRED, MAINTENANCE")
            @RequestParam(required = false) String status,

            @Parameter(description = "Case-insensitive partial name search")
            @RequestParam(required = false) String search,

            @Parameter(description = "Case-insensitive partial location search")
            @RequestParam(required = false) String location,

            @Parameter(description = "Zero-based page index", example = "0")
            @RequestParam(defaultValue = "0") int page,

            @Parameter(description = "Page size between 1 and 100", example = "25")
            @RequestParam(defaultValue = "25") int size,

            @Parameter(description = "Sort field: name, createdAt, status, id", example = "name")
            @RequestParam(defaultValue = "name") String sort,

            @Parameter(description = "Sort direction: asc, desc", example = "asc")
            @RequestParam(defaultValue = "asc") String direction) {

        EquipmentSearchQuery query = EquipmentSearchQuery.from(
                categoryId, status, search, location, page, size, sort, direction);
        return EquipmentPageResponse.from(equipmentService.findAll(query));
    }

    // POST /api/v1/equipment/{id}/out-of-service

    @PostMapping("/{id}/out-of-service")
    @Operation(summary = "Mark equipment out of service",
            description = """
                Transitions equipment from AVAILABLE to OUT_OF_SERVICE.
                Permitted roles: ADMIN.
                Requires a non-blank reason (max 2000 chars) and current version.
                """)
    @ApiResponse(responseCode = "200", description = "Equipment marked out of service")
    @ApiResponse(responseCode = "400", description = "Validation failed")
    @ApiResponse(responseCode = "401", description = "Authentication required")
    @ApiResponse(responseCode = "403", description = "Insufficient role or missing CSRF token")
    @ApiResponse(responseCode = "404", description = "Equipment not found")
    @ApiResponse(responseCode = "409", description = "Invalid transition, version conflict, or state conflict")
    EquipmentResponse markOutOfService(
            @PathVariable UUID id,
            @Valid @RequestBody StatusTransitionRequest request,
            Authentication authentication) {
        return EquipmentResponse.from(
                equipmentService.markOutOfService(
                        request.toOutOfServiceCommand(id), actor(authentication)));
    }

    // ── POST /api/v1/equipment/{id}/available

    @PostMapping("/{id}/available")
    @Operation(summary = "Mark equipment available",
            description = """
                Transitions equipment from OUT_OF_SERVICE to AVAILABLE.
                Permitted roles: ADMIN.
                Requires a non-blank reason (max 2000 chars) and current version.
                """)
    @ApiResponse(responseCode = "200", description = "Equipment marked available")
    @ApiResponse(responseCode = "400", description = "Validation failed")
    @ApiResponse(responseCode = "401", description = "Authentication required")
    @ApiResponse(responseCode = "403", description = "Insufficient role or missing CSRF token")
    @ApiResponse(responseCode = "404", description = "Equipment not found")
    @ApiResponse(responseCode = "409", description = "Invalid transition, version conflict, or state conflict")
    EquipmentResponse markAvailable(
            @PathVariable UUID id,
            @Valid @RequestBody StatusTransitionRequest request,
            Authentication authentication) {
        return EquipmentResponse.from(
                equipmentService.markAvailable(
                        request.toAvailableCommand(id), actor(authentication)));
    }

    // POST /api/v1/equipment/{id}/retire

    @PostMapping("/{id}/retire")
    @Operation(summary = "Retire equipment",
            description = """
                Permanently retires equipment. RETIRED is a terminal state; no
                further transitions are possible after this operation.
                Permitted roles: ADMIN only.
                Source status: AVAILABLE or OUT_OF_SERVICE.
                Requires a non-blank reason (max 2000 chars) and current version.
                """)
    @ApiResponse(responseCode = "200", description = "Equipment retired")
    @ApiResponse(responseCode = "400", description = "Validation failed")
    @ApiResponse(responseCode = "401", description = "Authentication required")
    @ApiResponse(responseCode = "403", description = "Insufficient role or missing CSRF token")
    @ApiResponse(responseCode = "404", description = "Equipment not found")
    @ApiResponse(responseCode = "409", description = "Invalid transition, version conflict, or state conflict")
    EquipmentResponse retire(
            @PathVariable UUID id,
            @Valid @RequestBody StatusTransitionRequest request,
            Authentication authentication) {
        return EquipmentResponse.from(
                equipmentService.retire(
                        request.toRetireCommand(id), actor(authentication)));
    }

    //exception handlers

    @ExceptionHandler(EquipmentValidationException.class)
    ResponseEntity<ProblemDetail> handleValidation(
            EquipmentValidationException exception) {

        return ResponseEntity.badRequest()
                .body(
                        ApiProblemFactory.create(
                                HttpStatus.BAD_REQUEST,
                                "EQUIPMENT_VALIDATION_FAILED",
                                "The equipment request is invalid."));
    }

    @ExceptionHandler(EquipmentNotFoundException.class)
    ResponseEntity<ProblemDetail> handleNotFound(
            EquipmentNotFoundException exception) {

        return ResponseEntity.status(
                        HttpStatus.NOT_FOUND)
                .body(
                        ApiProblemFactory.create(
                                HttpStatus.NOT_FOUND,
                                "EQUIPMENT_NOT_FOUND",
                                "The requested equipment was not found."));
    }

    @ExceptionHandler(EquipmentCategoryNotFoundException.class)
    ResponseEntity<ProblemDetail> handleCategoryNotFound(
            EquipmentCategoryNotFoundException exception) {

        return ResponseEntity.status(
                        HttpStatus.NOT_FOUND)
                .body(
                        ApiProblemFactory.create(
                                HttpStatus.NOT_FOUND,
                                "EQUIPMENT_CATEGORY_NOT_FOUND",
                                "The requested equipment category was not found."));
    }

    @ExceptionHandler(EquipmentCategoryInactiveException.class)
    ResponseEntity<ProblemDetail> handleCategoryInactive(
            EquipmentCategoryInactiveException exception) {

        return ResponseEntity.status(
                        HttpStatus.CONFLICT)
                .body(
                        ApiProblemFactory.create(
                                HttpStatus.CONFLICT,
                                "EQUIPMENT_CATEGORY_INACTIVE",
                                "The selected equipment category is inactive."));
    }

    @ExceptionHandler(DuplicateSerialNumberException.class)
    ResponseEntity<ProblemDetail> handleDuplicateSerial(
            DuplicateSerialNumberException exception) {

        return ResponseEntity.status(
                        HttpStatus.CONFLICT)
                .body(
                        ApiProblemFactory.create(
                                HttpStatus.CONFLICT,
                                "DUPLICATE_EQUIPMENT_SERIAL",
                                "An equipment item with that serial number already exists."));
    }

    @ExceptionHandler(EquipmentVersionConflictException.class)
    ResponseEntity<ProblemDetail> handleVersionConflict(
            EquipmentVersionConflictException exception) {

        return ResponseEntity.status(
                        HttpStatus.CONFLICT)
                .body(
                        ApiProblemFactory.create(
                                HttpStatus.CONFLICT,
                                "EQUIPMENT_VERSION_CONFLICT",
                                "The equipment was modified by another request."));
    }

    @ExceptionHandler(EquipmentStateConflictException.class)
    ResponseEntity<ProblemDetail> handleStateConflict(
            EquipmentStateConflictException exception) {

        return ResponseEntity.status(
                        HttpStatus.CONFLICT)
                .body(
                        ApiProblemFactory.create(
                                HttpStatus.CONFLICT,
                                "EQUIPMENT_STATE_CONFLICT",
                                "The requested equipment status transition is not allowed."));
    }

    // Authentication
    private static AuthenticatedActor actor(
            Authentication authentication) {

        CoachGymUserPrincipal principal =
                (CoachGymUserPrincipal)
                        authentication.getPrincipal();

        return principal.authenticatedActor();
    }
}
